apiVersion: apigee.apigeebasictwo.jet.crossplane.io/v1alpha1
kind: User
metadata:
  name: abtwouserone
spec:
  providerConfigRef:
   name: abtwoprvcfg
  providerRef:
   name: drsurya-prv
  writeConnectionSecretToRef:
   name: usrconnsec
   namespace: upbound-system
  forProvider:
    emailId: "suryamohan99m@gmail.com"
    firstName: "Surya"
    lastName: "Mohan"
    passwordSecretRef:
      key: userkey
      name: userkeysec
      namespace: upbound-system